apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kubeflow-007
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/istio-crds
    name: istio-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/istio-install
    name: istio-install
  - kustomizeConfig:
      parameters:
      - name: clusterRbacConfig
        value: "ON"
      repoRef:
        name: manifests
        path: istio/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kubeflow-roles
    name: kubeflow-roles
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      overlays:
      - istio
      - application
      repoRef:
        name: manifests
        path: argo
    name: argo
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: admission-webhook/webhook
    name: webhook
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: webhookNamePrefix
        value: admission-webhook-
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap
    name: bootstrap
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      repoRef:
        name: manifests
        path: jupyter/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      overlays:
      - istio
      - application
      repoRef:
        name: manifests
        path: metadata
    name: metadata
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: injectGcpCredentials
        value: "true"
      repoRef:
        name: manifests
        path: jupyter/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: knative-serving
      repoRef:
        name: manifests
        path: knative/knative-serving-crds
    name: knative-crds
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: knative-serving
      repoRef:
        name: manifests
        path: knative/knative-serving-install
    name: knative-install
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: kfserving/kfserving-crds
    name: kfserving-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: kfserving/kfserving-install
    name: kfserving-install
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: usageId
        value: "6028077219354610138"
      - name: reportUsage
        value: "true"
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: tensorboard
    name: tensorboard
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: tf-training/tf-job-crds
    name: tf-job-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: katib/katib-crds
    name: katib-crds
  - kustomizeConfig:
      overlays:
      - application
      - istio
      repoRef:
        name: manifests
        path: katib/katib-controller
    name: katib-controller
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/api-service
    name: api-service
  - kustomizeConfig:
      overlays:
      - minioPd
      - application
      parameters:
      - name: minioPd
        value: kubeflow-007-storage-artifact-store
      - name: minioPvName
        value: minio-pv
      - name: minioPvcName
        value: minio-pv-claim
      repoRef:
        name: manifests
        path: pipeline/minio
    name: minio
  - kustomizeConfig:
      overlays:
      - mysqlPd
      - application
      parameters:
      - name: mysqlPd
        value: kubeflow-007-storage-metadata-store
      - name: mysqlPvName
        value: mysql-pv
      - name: mysqlPvcName
        value: mysql-pv-claim
      repoRef:
        name: manifests
        path: pipeline/mysql
    name: mysql
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/persistent-agent
    name: persistent-agent
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/pipelines-runner
    name: pipelines-runner
  - kustomizeConfig:
      overlays:
      - gcp
      - istio
      - application
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui
    name: pipelines-ui
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/pipelines-viewer
    name: pipelines-viewer
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/scheduledworkflow
    name: scheduledworkflow
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/pipeline-visualization-service
    name: pipeline-visualization-service
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: gcp/cloud-endpoints
    name: cloud-endpoints
  - kustomizeConfig:
      overlays:
      - application
      - istio
      parameters:
      - name: admin
        value: terence@growingdata.com.au
      - name: userid-header
        value: X-Goog-Authenticated-User-Email
      - name: userid-prefix
        value: 'accounts.google.com:'
      - name: gcp-sa
        value: kubeflow-007-user@grwdt-dev.iam.gserviceaccount.com
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: gcp/gpu-driver
    name: gpu-driver
  - kustomizeConfig:
      overlays:
      - managed-cert
      - application
      parameters:
      - name: namespace
        value: istio-system
      - name: ipName
        value: kubeflow-007-ip
      - name: hostname
        value: kubeflow-007.endpoints.grwdt-dev.cloud.goog
      repoRef:
        name: manifests
        path: gcp/iap-ingress
    name: iap-ingress
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: seldon/seldon-core-operator
    name: seldon-core-operator
  - kustomizeConfig:
      parameters:
      - name: user
        value: terence@growingdata.com.au
      - name: profile-name
        value: kubeflow-terence
      repoRef:
        name: manifests
        path: default-install
    name: default-install
  plugins:
  - kind: KfGcpPlugin
    metadata:
      creationTimestamp: null
      name: gcp
    spec:
      auth:
        iap:
          oAuthClientId: 350840923736-7udplj6q6jdmq7lognfmr4d5l7h54t3i.apps.googleusercontent.com
          oAuthClientSecret:
            name: CLIENT_SECRET
      createPipelinePersistentStorage: true
      deploymentManagerConfig:
        repoRef:
          name: manifests
          path: gcp/deployment_manager_configs
      email: terence@growingdata.com.au
      enableWorkloadIdentity: true
      hostname: kubeflow-007.endpoints.grwdt-dev.cloud.goog
      ipName: kubeflow-007-ip
      project: grwdt-dev
      skipInitProject: true
      useBasicAuth: false
      zone: australia-southeast1-a
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz
  secrets:
  - name: CLIENT_SECRET
    secretSource:
      envSource:
        name: CLIENT_SECRET
  version: master
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-0.7-branch"'
    name: manifests
  - localPath: '".cache/manifests/manifests-0.7-branch"'
    name: manifests
  - localPath: '".cache/manifests/manifests-0.7-branch"'
    name: manifests
